#!/usr/bin/with-contenv bash

[[ ! -d /app/htpcmanager/.git ]] && (git clone https://github.com/Hellowlol/HTPC-Manager.git /app/htpcmanager && \
chown -R mab:mab /app)

# opt out for autoupdates
[ "$ADVANCED_DISABLEUPDATES" ] && exit 0

cd /app/htpcmanager
git pull
chown -R mab:mab /app
